version: "2.3"
services:
  stylegan2-web:
    image: ${DOCKER_IMAGE:-stylegan2-web}:${DOCKER_IMAGE_VERSION:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
    # user: ${LOCAL_USER:-1000:1000}
    runtime: nvidia
    volumes:
      - ".:/app/"
    env_file:
      - .env
    ports:
      - "9000:9000"
    command: [ "python3","./http_server.py" ]
#    labels:
#      - "traefik.enable=true"
#      - "traefik.backend=flask"
#      - "traefik.frontend.rule=${TRAEFIK_FRONTEND_RULE}"
#      - "traefik.port=9000"
#      - "traefik.docker.network=traefik"
#
#  traefik:
#    image: traefik:v1.7
#    networks:
#      - traefik
#      - default
#    env_file:
#      - .env
#    labels:
#      - "traefik.acme.email=${TRAEFIK_ACME_EMAIL:? Missing TRAEFIK_ACME_EMAIL env var.}"
#      - "traefik.docker.domain=${TRAEFIK_DOCKER_DOMAIN:? Missing TRAEFIK_DOCKER_DOMAIN env var.}"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
#      - ./traefik/acme:/etc/traefik/acme
#    ports:
#      - "80:80"
#      - "443:443"
#      - "8080:8080"
#    command:
#      --docker \
#      --docker.watch \
#      --docker.exposedbydefault=false \
#      --constraints=tag==${TRAEFIK_TAG} \
#      --logLevel=DEBUG \
#      --accessLog \
#      --web
#networks:
#  traefik:
#    external: true