version: "2.3"
services:
  stylegan2-web:
    image: ${DOCKER_IMAGE:-stylegan2-web}:${DOCKER_IMAGE_VERSION:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
    # user: ${LOCAL_USER:-1000:1000}
    runtime: nvidia
    volumes:
      - ".:/app/"
    env_file:
      - .env
    ports:
      - "9000:9000"
    command: [ "python3","./http_server.py" ]
  tensorboard:
    image: tensorboard:${DOCKER_IMAGE_VERSION:-latest}
    build:
      context: .
      dockerfile: ./tensorboard.Dockerfile
    ports:
      - 6006:6006
    command: tensorboard --logdir=/notebooks/graphs